### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by rdeits** [vye16/corner-camera#1]
Hi there! Thanks for making the code for this project available. I'm playing around with my own implementation of the cornercam (for a 6.865 class project, actually), but I noticed that there's no license for this project so, technically, its code can't be reused or modified. Would you be willing to add some open-source friendly license to the project? If your intent is to let people use the code without restriction, then [MIT](https://opensource.org/licenses/MIT) is probably a sensible choice, but it's of course up to you.

**Comment by vye16** [comment]
Hey, thanks for reaching out! I’ve added a license, let me know how it goes!

Thanks,
Vickie

**Comment by rdeits** [comment]
Thank you! I've put up my implementation here: https://github.com/rdeits/EdgeCameras.jl/blob/gh-pages/notebooks/demo.ipynb
